# 缩进：2空格
# 基础信息
base:
  pc_name: "Desktop"
  game_mode: "黄沙百炼"

# PVE-黄沙百炼参数
hsbl:
  # 电脑1：台式机
  desktop:
    #出生点p1
    p1:
      sleep: 1000 #休眠
    #从p1前往p2
    p2:
      run: [1020,1000]
      move: [315,-110]
      sleep: 200
    #从p2前往p3
    p3:
      sleep: 3000
    #从p3前往p4
    p4:
      run: [1400,1000]
      move: [-110,-25]
    #钩锁空中平台p5飞袭到p6
    p5p6:
      sleep1: 1700  # 按Q出飞索到飞袭的时间
      sleep2: 2700  # 等待钩锁飞袭完成，落地
    #从p6前往p7
    p7:
      run: [2500,1000]
      move1: [-415,207] #调整视角，F技能攻击小怪
      move2: [-150,0]    #调整视角，向左转
    #从p7前往p8，再前往p8.5， 再前往p9
    p8:
      run1: [1230,1000]  #奔跑到p8
      move1: [-190,-55]  #调整视角，朝向p8.5， 现在大概是挂壁状态
      walk: 660         #走到p8.5
      move2: [-580,0]    #调整视角，朝向p8.5
      move3: [580,0]     #调整视角，朝向p9
      run2: [680,1000]   #奔跑到p9
    #在p9点执行攻击操作
    p9:
      move1: [260,-20]   #调整视角，朝向方向1
      move2: [-106,60]   #调整视角，朝向方向2
    #从p9前往p10
    p10:
      move: [-70,0]     #调整视角，朝向p10
      run: [1700,1000]  #奔跑到p10
    #在p11朝3个方向攻击蚊子，再转向宝箱
    p11:
      move1: [60,-75]    #调整视角，朝向方向1
      move2: [295,0]    #调整视角，朝向方向2
      move3: [127,0]    #调整视角，朝向方向3
      move4: [-127,0]    #调整视角，朝向宝箱
    #从p11前往p12，并一边跑一边E开箱
    p12:
      run: [1200,120]
  
  # 电脑2：Thinkbook16P
  thinkbook16p:
    #出生点p1
    p1:
      sleep: 1000 #休眠
    #从p1前往p2
    p2:
      run: [1020,1000]
      move: [315,110]
      sleep: 200
    #从p2前往p3
    p3:
      sleep: 3000
    #从p3前往p4
    p4:
      run: [1400,1000]
      move: [-103,-32]
    #钩锁空中平台p5飞袭到p6
    p5p6:
      sleep1: 1600  # 按Q出飞索到飞袭的时间
      sleep2: 2000  # 等待钩锁飞袭完成，落地
    #从p6前往p7
    p7:
      run: [3650,1000]
      move1: [-415,207] #调整视角，F技能攻击小怪
      move2: [-150,0]    #调整视角，向左转
    #从p7前往p8，再前往p8.5， 再前往p9
    p8:
      run1: [2200,1000]  #奔跑到p8
      move1: [-213,-61]  #调整视角，朝向临时位置， 现在大概是挂壁状态
      walk: 660         #走到p8.5
      move2: [-580,0]    #调整视角，朝向p8.5
      move3: [580,0]     #调整视角，朝向p9
      run2: [400,1000]   #奔跑到p9
    #在p9点执行攻击操作
    p9:
      move1: [265,-20]   #调整视角，朝向方向1
      move2: [-106,60]   #调整视角，朝向方向2
    #从p9前往p10
    p10:
      move: [-70,0]     #调整视角，朝向p10
      run: [1700,1000]  #奔跑到p10
    #在p11朝3个方向攻击蚊子，再转向宝箱
    p11:
      move1: [60,-75]    #调整视角，朝向方向1
      move2: [298,0]    #调整视角，朝向方向2
      move3: [150,0]    #调整视角，朝向方向3
      move4: [-150,0]    #调整视角，朝向宝箱
    #从p11前往p12，并一边跑一边E开箱
    p12:
      run: [1200,120]
   
  # 电脑3：无界14X
  wujie14x:
    #出生点p1
    p1:
      sleep: 1000 #休眠
    #从p1前往p2
    p2:
      run: [1020,1000]
      move: [315,110]
      sleep: 200
    #从p2前往p3
    p3:
      sleep: 3000
    #从p3前往p4
    p4:
      run: [1400,1000]
      move: [-110,-25]
    #钩锁空中平台p5飞袭到p6
    p5p6:
      sleep1: 1700  # 按Q出飞索到飞袭的时间
      sleep2: 2700  # 等待钩锁飞袭完成，落地
    #从p6前往p7
    p7:
      run: [3650,1000]
      move1: [-415,207] #调整视角，F技能攻击小怪
      move2: [-150,0]    #调整视角，向左转
    #从p7前往p8，再前往p8.5， 再前往p9
    p8:
      run1: [2200,1000]  #奔跑到p8
      move1: [-190,-55]  #调整视角，朝向p8.5， 现在大概是挂壁状态
      walk: 660         #走到p8.5
      move2: [-580,0]    #调整视角，朝向p8.5
      move3: [580,0]     #调整视角，朝向p9
      run2: [400,1000]   #奔跑到p9
    #在p9点执行攻击操作
    p9:
      move1: [265,-20]   #调整视角，朝向方向1
      move2: [-106,60]   #调整视角，朝向方向2
    #从p9前往p10
    p10:
      move: [-70,0]     #调整视角，朝向p10
      run: [1700,1000]  #奔跑到p10
    #在p11朝3个方向攻击蚊子，再转向宝箱
    p11:
      move1: [60,-75]    #调整视角，朝向方向1
      move2: [298,0]    #调整视角，朝向方向2
      move3: [150,0]    #调整视角，朝向方向3
      move4: [-150,0]    #调整视角，朝向宝箱
    #从p11前往p12，并一边跑一边E开箱
    p12:
      run: [1200,120]
  
  # 电脑4：服务器
  myserver:
    #出生点p1
    p1:
      sleep: 1000 #休眠
    #从p1前往p2
    p2:
      run: [1020,1000]
      move: [315,-110]
      sleep: 200
    #从p2前往p3
    p3:
      sleep: 4000
    #从p3前往p4
    p4:
      run: [1400,1000]
      move: [-110,-25]
    #钩锁空中平台p5飞袭到p6
    p5p6:
      sleep1: 1600  # 按Q出飞索到飞袭的时间
      sleep2: 3000  # 等待钩锁飞袭完成，落地
    #从p6前往p7
    p7:
      run: [3650,1000]
      move1: [-415,207] #调整视角，F技能攻击小怪
      move2: [-150,0]    #调整视角，向左转
    #从p7前往p8，再前往p8.5， 再前往p9
    p8:
      run1: [1182,1000]  #奔跑到p8
      move1: [-193,-55]  #调整视角，朝向p8.5， 现在大概是挂壁状态
      walk: 660         #走到p8.5
      move2: [-580,0]    #调整视角，朝向p8.5
      move3: [580,0]     #调整视角，朝向p9
      run2: [725,1000]   #奔跑到p9
    #在p9点执行攻击操作
    p9:
      move1: [260,-20]   #调整视角，朝向方向1
      move2: [-106,60]   #调整视角，朝向方向2
    #从p9前往p10
    p10:
      move: [-70,0]     #调整视角，朝向p10
      run: [1700,1000]  #奔跑到p10
    #在p11朝3个方向攻击蚊子，再转向宝箱
    p11:
      move1: [60,-75]    #调整视角，朝向方向1
      move2: [305,0]    #调整视角，朝向方向2
      move3: [150,0]    #调整视角，朝向方向3
      move4: [-150,0]    #调整视角，朝向宝箱
    #从p11前往p12，并一边跑一边E开箱
    p12:
      run: [1200,120]
  